# Generated by Django 5.0 on 2024-01-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mouhami_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.IntegerField(),
        ),
    ]
