# Generated by Django 5.0.1 on 2024-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0002_remove_booking_review_review_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
