# Generated by Django 5.0.1 on 2024-01-24 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0003_alter_lawyer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lawyer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mouhami_api.lawyer'),
            preserve_default=False,
        ),
    ]
