# Generated by Django 5.0 on 2024-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0003_alter_lawyer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='wilaya',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, to='mouhami_api.review'),
        ),
    ]
