# Generated by Django 5.0 on 2024-01-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouhami_api', '0004_rename_wilaya_lawyer_location_alter_lawyer_reviews'),
        ('mouhami_api', '0004_review_lawyer_id'),
    ]

    operations = [
    ]
